server:
  port: 8764

spring:
  application:
    name: consumer
  redis:
    host: 112.74.29.31
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: 123456
    #消费端配置  手动接收  限流
  rabbitmq:
    addresses: 112.74.29.31:5672
    username: guest
    password: guest
    virtual-host: / #连接到rabbitMQ的vhost
    connection-timeout: 15000 # 连接超时，单位毫秒，0表示无穷大，不超时
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        prefetch: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


