server:
  port: 8763

spring:
  application:
    name: producer
  redis:
    host: 112.74.29.31
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: 123456
  rabbitmq:
    addresses: 112.74.29.31:5672
    username: guest
    password: guest
    virtual-host: / #连接到rabbitMQ的vhost
    connection-timeout: 15000 # 连接超时，单位毫秒，0表示无穷大，不超时
    publisher-returns: true # 是否启用【发布返回】
    template:
      mandatory: true #启用强制信息；默认false
    listener:
      direct:
        acknowledge-mode: manual
    publisher-confirms: true #是否启用【发布确认】

  datasource:
    url: jdbc:mysql://112.74.29.31:3306/test?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  type-aliases-package: com.hjy.yyyproducer.mapper
  mapper-locations: classpath*:/mapper/*.xml
